### ISSUE TITLE
关于此接口的时效性

### ISSUE THREAD

**Issue by z0z0r4** [LxHTT/MCSLDownloaderAPI#1]
是否考虑使用 GitHub Actions 来自动更新 release 呢？

**Comment by LxHTT** [comment]
因为这个API的所有源文件都是我**手工**搞的，所以时效性可能无法保证（
而且有3个地方存储文件，目前没法想到什么自动化方案（
不过最难的是sharepoint的文件生成永久直链的问题，其他都好说

**Comment by z0z0r4** [comment]
> 因为这个API的所有源文件都是我**手工**搞的，所以时效性可能无法保证（ 而且有3个地方存储文件，目前没法想到什么自动化方案（ 不过最难的是sharepoint的文件生成永久直链的问题，其他都好说

我不了解 GUI，打算直接学 C# 的...没法在主项目上帮你，不过如果你需要，我可以提供个镜像源倒是，或者说自动化

**Comment by LxHTT** [comment]
- 官方源没钱。
 - SharePoint过一段时间就会恢复，我今天下午还正常，今天应该是突发状况
 - GitHub、Gitee请求支援

**Comment by xianyongjian080402** [comment]
乐，把exe放在源码里也是个秀儿

**Comment by z0z0r4** [comment]
> * 官方源没钱。
> * SharePoint过一段时间就会恢复，我今天下午还正常，今天应该是突发状况
> * GitHub、Gitee请求支援

您理解的官方源是你提供吗？那叫 
> 我可以提供个自动化方案，或者干脆一个 brand-new 的镜像源
我指的是 mojang.com

**Comment by z0z0r4** [comment]
> 乐，把exe放在源码里也是个秀儿

不清楚，真的的话...py打包已经26MB了，都比官方老版本一个服务端jar大了 :(

**Comment by LxHTT** [comment]
mojang就一个原版服务端，没什么好提供的

**Comment by z0z0r4** [comment]
> mojang就一个原版服务端，没什么好提供的

您不打算从保底从官方源下载服务端吗？...

**Comment by xianyongjian080402** [comment]
> > 乐，把exe放在源码里也是个秀儿
> 
> 不清楚，真的的话...py打包已经26MB了，都比官方老版本一个服务端jar大了 :(

hh，这不很正常吗，py的打包生态就是一坨屎（

**Comment by z0z0r4** [comment]
> > > 乐，把exe放在源码里也是个秀儿
> > 
> > 
> > 不清楚，真的的话...py打包已经26MB了，都比官方老版本一个服务端jar大了 :(
> 
> hh，这不很正常吗，py的打包生态就是一坨屎（

GG

**Comment by LxHTT** [comment]
shit报：体积比以前都小了好多，但还是答辩

**Comment by z0z0r4** [comment]
> shit报：体积比以前都小了好多，但还是答辩

体积歪楼啦

真没打算过从官方下服务端？

**Comment by LxHTT** [comment]
不搞

**Comment by z0z0r4** [comment]
我是傻逼
